env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  no-unused-vars: 0
  no-param-reassign: 0
  import/no-cycle: 0
  react/prop-types: 0
